default_context:
  project_name: 'clinic-mobile'
  project_slug: 'clinic-mobile'
  domain_main: 'clinic-mobile.com'
  domain_staging: 'stag.clinic-mobile.com'
  docker_swarm_stack_name_main: 'clinic-mobile-com'
  docker_swarm_stack_name_staging: 'stag-clinic-mobile-com'
  secret_key: 'b823248645244512113e90c20f3386c148dde45d8230ef4ea666756b7ed15ff1'
  first_superuser: 'admin@clinic-mobile.com'
  first_superuser_password: '286b4b7f1611358e980190ec97ec5a49d09b650f949a3eddfba57c5db0acc9dc'
  backend_cors_origins: '["http://localhost", "http://localhost:4200","https://localhost:3000", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.clinic-mobile.com", "https://stag.clinic-mobile.com", "https://clinic-mobile.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@clinic-mobile.com'
  postgres_password: 'd18f1097bceb667706d459b940f39001c87fa513e53786f15337332c73d291af'
  pgadmin_default_user: 'admin@clinic-mobile.com'
  pgadmin_default_user_password: '286b4b7f1611358e980190ec97ec5a49d09b650f949a3eddfba57c5db0acc9dc'
  traefik_constraint_tag: 'clinic-mobile.com'
  traefik_constraint_tag_staging: 'stag.clinic-mobile.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:286b4b7f1611358e980190ec97ec5a49d09b650f949a3eddfba57c5db0acc9dc'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
