"""ClinicBooking and ClinicBookingLog models added

Revision ID: 182d154c5582
Revises: d55f77cd58de
Create Date: 2021-06-05 20:27:44.918953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182d154c5582'
down_revision = 'd55f77cd58de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookinglog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookinglog_id'), 'bookinglog', ['id'], unique=False)
    op.create_table('clinicbooking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinicbooking_id'), 'clinicbooking', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinicbooking_id'), table_name='clinicbooking')
    op.drop_table('clinicbooking')
    op.drop_index(op.f('ix_bookinglog_id'), table_name='bookinglog')
    op.drop_table('bookinglog')
    # ### end Alembic commands ###
